version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "mcansh"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: "10:00"
      timezone: "America/Detroit"
    assignees:
      - "mcansh"
    groups:
      "remix":
        patterns:
          - "@remix-run/*"
          - "remix"
      "vitest":
        patterns:
          - "@vitest/*"
          - "vitest"
      "prisma":
        patterns:
          - "@prisma/*"
          - "prisma"
      "tailwindcss":
        patterns:
          - "@tailwindcss/*"
          - "tailwindcss"
      "oxc":
        patterns:
          - "oxlint"
          - "oxfmt"
