allowBuilds:
  "@prisma/engines": true
  "@remix-run/assert": true
  "@remix-run/async-context-middleware": true
  "@remix-run/auth": true
  "@remix-run/auth-middleware": true
  "@remix-run/cli": true
  "@remix-run/component": true
  "@remix-run/compression-middleware": true
  "@remix-run/cookie": true
  "@remix-run/cop-middleware": true
  "@remix-run/cors-middleware": true
  "@remix-run/csrf-middleware": true
  "@remix-run/data-schema": true
  "@remix-run/data-table": true
  "@remix-run/data-table-mysql": true
  "@remix-run/data-table-postgres": true
  "@remix-run/data-table-sqlite": true
  "@remix-run/fetch-proxy": true
  "@remix-run/fetch-router": true
  "@remix-run/file-storage": true
  "@remix-run/file-storage-s3": true
  "@remix-run/form-data-middleware": true
  "@remix-run/form-data-parser": true
  "@remix-run/fs": true
  "@remix-run/headers": true
  "@remix-run/html-template": true
  "@remix-run/lazy-file": true
  "@remix-run/logger-middleware": true
  "@remix-run/method-override-middleware": true
  "@remix-run/mime": true
  "@remix-run/multipart-parser": true
  "@remix-run/node-fetch-server": true
  "@remix-run/response": true
  "@remix-run/route-pattern": true
  "@remix-run/session": true
  "@remix-run/session-middleware": true
  "@remix-run/session-storage-memcache": true
  "@remix-run/session-storage-redis": true
  "@remix-run/static-middleware": true
  "@remix-run/tar-parser": true
  "@remix-run/test": true
  esbuild: true
  msw: true
  prisma: true
  remix: true
catalog:
  "@mcansh/http-helmet": ^0.13.2
  "@mcansh/remix-testing-library": ^0.0.1
  "@mcansh/vite-plugin-remix": ^0.0.1
  "@mcansh/vite-plugin-svg-sprite": ^0.7.1
  "@mswjs/http-middleware": ^0.10.3
  "@oxlint/plugins": ^1.58.0
  "@prisma/adapter-pg": ^7.7.0
  "@prisma/client": ^7.7.0
  "@redwoodjs/agent-ci": ^0.9.0
  "@remix-run/cli": github:remix-run/remix#preview/pr-11204&path:packages/cli
  "@standard-schema/spec": ^1.1.0
  "@tailwindcss/vite": ^4.2.2
  "@total-typescript/tsconfig": ^1.0.4
  "@types/node": ^25.5.2
  "@vitest/coverage-v8": ^4.1.4
  "@vitest/ui": 4.1.4
  bcryptjs: ^3.0.3
  bullmq: ^5.73.4
  clsx: ^2.1.1
  date-fns: ^4.1.0
  happy-dom: ^20.8.9
  ioredis: ^5.10.1
  msw: ^2.13.0
  prisma: ^7.7.0
  remix: github:remix-run/remix#preview/main&path:packages/remix
  tailwindcss: ^4.2.2
  typescript: ^6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-devtools-json: ^1.0.0
  vite-plus: ^0.1.16
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: strict
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

shellEmulator: true
