name: 🛠️ CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  DATABASE_URL: postgresql://postgres:password@localhost:5432/remix_wordle_test
  REDIS_URL: redis://localhost:6379
  SESSION_SECRET: thisisaverysecuresecret1234567890

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: ✅ Check
    if: github.repository == 'mcansh/remix-wordle'

    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup VP
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: ✅ Type check & lint
        run: vp check

  test:
    name: 🧪 Test
    if: github.repository == 'mcansh/remix-wordle'

    runs-on: ubuntu-slim
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup VP
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: 🧪 Run Tests
        run: vp test

  build:
    name: 🛠️ Build
    if: github.repository == 'mcansh/remix-wordle'

    runs-on: ubuntu-slim
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup VP
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: 🛠️ Build
        run: vp build
