name: 🧪 Test

on:
  push:
  pull_request:

env:
  DATABASE_URL: postgresql://postgres:password@localhost:5432/remix_wordle_test
  REDIS_URL: redis://localhost:6379
  SESSION_SECRET: thisisaverysecuresecret1234567890

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ⚙️ Build
    runs-on: ubuntu-slim
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true

      - name: ⚡️ Install Dependencies
        run: vp install

      - name: ✅ Run Checks
        run: vp check

      - name: 🏗 Build
        run: vp build

  test:
    name: 🧪 Test
    runs-on: ubuntu-slim
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⚡️ Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true

      - name: ⚡️ Install Dependencies
        run: vp install

      - name: ✅ Run Checks
        run: vp check

      - name: 🧪 Run Tests
        run: vp test
